config/routes.rb
Humanweb::Application.routes.draw do

  devise_for :users

  get "home/index", :as => 'root'
  root :to => 'home#index'

  get "team" => 'home#team', :as => :team
  get "contact" => 'home#contact', :as => :contact

  scope :controller => :portfolio do
    get 'work'=> :index
    get 'work/ssh' => :southsidehealth, :as => :work_southsidehealth
    get 'work/helparoundtown' => :helparoundtown
    get 'work/globalgreenarts' => :globalgreenarts
    get 'work/projectevie' => :projectevie
    get 'work/rentstuff' => :rentstuff
    get 'work/purplebinder' => :purplebinder
  end

  resources :posts, :path => 'blog'

  # For EC2 profiling research
  resources :benchmark_results

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    can :manage, :all
    if user.nil?
      cannot :manage, Post
      can :read, Post
    end
  end
    
end

app/models/benchmark_result.rb
class BenchmarkResult < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_url :title, :sync_url => true   # for making slugs with Stringex

  belongs_to :author, :class_name => 'User'
  
  def to_param
    url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts, :foreign_key => :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do
    flash.alert = 'Sign in, buddy.'
    redirect_to new_user_session_path
  end

end

app/controllers/benchmark_results_controller.rb
class BenchmarkResultsController < ApplicationController

  def create
    @br = BenchmarkResult.new(params[:benchmark_result])
    @br.save
    render 'index'
  end

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def team
  end

  def contact
  end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def index
    render :layout => 'application'
  end

  def helparoundtown
  end

  def southsidehealth
  end

  def globalgreenarts
  end

  def projectevie
  end

end

app/controllers/posts_controller.rb
# Blog Posts
class PostsController < ApplicationController
  layout 'blog'
  load_and_authorize_resource :find_by => :url  # this is a Devise method

  def create
    @post.author = current_user
    save @post
  end

  def update
    save @post
  end

  def save post
    post.title = params[:post][:title]
    post.body = params[:post][:body]

    if post.save
      redirect_to post_path(post)
    else
      flash.alert = 'Failsauce.'
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/contact.html.haml
-content_for :title do
  Contact

.grid_12.headline-container.center
  
  %h1 Let&#8217;s talk about the next game-changer.

  %h2
    If you want to hire a smart, flexible, &amp; friendly team for
    your web project, we're it.

.clear

.grid_4.prefix_4.center.contact-info
  = image_tag 'logo-bigger.png'
  %br
  %h3 HUMANWEB
  %p
    talk@humanweb.co
    %br
    617 / 910 / 7317
  -#
    %div{:style=>'margin: 65px auto 0; width: 250px;'}
      %p{:style=>'text-align:left; font-size: 1.3em;'}
        = render 'shared/humanweb'
        %br
        talk (at) humanweb.co
        %br
        617.910.7317
      

app/views/home/index.html.haml
-content_for :title do
  Web Design, Rich Internet Applications, Software Consulting

.grid_12.headline-container

  %h1.center
    Humanweb builds online communities that solve problems.

  %h2.center
    Infrastructure | Graphic Design | Software Development

.content-area.frontpage
  .who
    .headline.clearfix
      .circle
      %h3 Who
    %p
      HUMANWEB
      is an enthusiastic tech studio based in
      <b>Chicago</b>.
      We are
      =link_to 'two full-time cofounders', team_path
      who work with a network of designers and developers.
      -#
        With expertise in areas from scalable infrastructure to
        graphic design, we take a <b>full-stack approach</b> to
        software development.
  .what
    .headline.clearfix
      .circle
      %h3 What
    %p
      
      We
      develop <b>scalable web
      apps</b> that are incredibly easy to use and solve
      real problems.
      -#
        We have provided turn-key technical solutions to
        startups and rescued floundering projects, always using
        the best tools for the job and up-to-date web standards. See our
        %strong= link_to 'case studies', work_path
        for more information.
      

  .how
    .headline.clearfix
      .circle
      %h3 How
    %p
      We work with <b>clients as partners</b>, so your approval
      is built in to our design process. We favor <b>Agile
      development</b>, starting from a minimalist design and iteratively
      adding more.
      -#
        At every step, we focus on building experiences
        rather than just sets of features.
        Best of all, we have fun doing it.

%a.hire-us.center{:href => contact_path}
  %h3 Hire Us

app/views/home/team.html.haml
-content_for :title do
  Team

.grid_12.headline-container.center
  %h1 Nice to meet you!
  %h2
    We develop long-term relationships with
    top-notch clients, bringing our energy and expertise
    to the table every single day.

.clear

.grid_6
  .person
    .image.joe
    .text
      %h3 Joseph Flesh
      %p
        Joe enjoys wearing many hats,
        from interface design to keeping books
        and being the main point of contact for clients. 
        Prior to humanweb, Joe researched simulation technologies at a
        Department of Energy laboratory, worked in corporate IT, and had a stint
        as a journalist. He enjoys long walks, world travel, and
        breakfast.

.grid_6
  .person
    .image.declan
    .text
      %h3 Declan Frye
      %p
        Declan is an exceptionally clear thinker, and often distills
        his thoughts into beautiful application specs.
        He's responsible for the
        heavy lifting in application architecture. A Manhattan native, he loves the
        weather and sailing in the Bay Area. He owns a wooden sailboat
        and studies Brazilian jujitsu.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      HUMANWEB -
      = yield :title
    <link rel="shortcut icon" href="/favicon.gif" />
    = stylesheet_link_tag 'reset'
    = stylesheet_link_tag '960'
    = stylesheet_link_tag 'default'
    = stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.16.custom'

    = javascript_include_tag 'jquery-1.6.4.min'
    = javascript_include_tag 'jquery-ui-1.8.16.custom.min'
    = javascript_include_tag 'easySlider1.7'
    = javascript_include_tag 'humanweb'

  %body
    #page-header
      .container_12
        .grid_5
          %h1#biglogo humanweb

          - @highlight ||= request.fullpath
        .grid_7{:style => 'display: relative;'}
          %ul#nav-menu
            - if @highlight == root_path
              %li.active= link_to "WHAT WE DO", root_path
            - else
              %li= link_to "WHAT WE DO", root_path

            - if @highlight == team_path
              %li.active= link_to "THE TEAM", team_path
            - else
              %li= link_to "THE TEAM", team_path

            - if @highlight.start_with?(work_path)
              %li.active= link_to "OUR WORK", work_path
            - else
              %li= link_to "OUR WORK", work_path

            - if @highlight.start_with?(posts_path)
              %li.active= link_to "BLOG", posts_path
            - else
              %li= link_to "BLOG", posts_path

            - if @highlight == contact_path
              %li.active= link_to "HIRE US", contact_path
            - else
              %li= link_to "HIRE US", contact_path
  
    #bodyContainer{:style=>'padding-bottom:20px;'}
      #bodyPage.container_12
        - if notice
          .notice= notice
        -if alert
          .notice.alert= alert

        = content_for?(:content) ? yield(:content) : yield

    #footerContainer 
      .container_12
        .grid_12#page-footer.node-right
          &copy; 2010-#{DateTime.now.year} Human Web Solutions LLC

app/views/layouts/blog.html.haml
- content_for :content do
  %section.blog

    .content.grid_8
      = content_for?(:blog_content) ? yield(:blog_content) : yield

    %nav.grid_4.right-sidebar
      .item.light-green.rounded-small
        %h3 Archive
        %ul
          - Post.all.each do |post|
            %li= link_to post.title, post_path(post), :class => 'text'

      .item.light-green.rounded-small
        %h3 Case Studies
        = render 'shared/casestudies'


=render :file =>'layouts/application'

app/views/layouts/portfolio.html.haml
- content_for :content do
  
  .headline-container.center
    %h1
      = yield :study_title
    %h2 Case study

  .content-area
    .grid_12
      .padding-30
        .back-to-portfolio
          %p= link_to "< back to portfolio", work_path, :class => 'light-grey'
      
        .left-column
          = yield :study_pics

        .right-column.study-body
          = yield :study_body
        
    .grid_12
      .padding-30
      .padding-30
        = render 'shared/casestudies' 

= render :template => 'layouts/application'

app/views/portfolio/globalgreenarts.html.haml
- content_for :title do
  Professional Wordpress Web Design
- content_for :study_title do
  Global Green Arts

- content_for :study_sidebar do
  .item.light-green.rounded-small
    %h3 Technology Used
    %ul
      %li HTML5 with CSS3
      %li PHP and Wordpress
      %li jQuery

- content_for :study_logo do
  = image_tag 'logo_globalgreen.png'

- content_for :study_pics do
  .body-slideshow
    %ul
      %li
        = image_tag 'screenshot-gga2.jpg'
      %li
        = image_tag 'screenshot-gga4.jpg'
      %li
        = image_tag 'screenshot-gga3.jpg'

  :javascript
    $('.body-slideshow ul li').css('height', '390px');
    $('.body-slideshow').easySlider({
      numeric: true,
      controlsBefore: '<div class="numeric-slide-controls">',
      controlsAfter: '</div>'
    });

  %blockquote.quote
    %p
      &#8220;The site
      looks fantastic, and it's super
      easy to edit and update. Humanweb has been easy to
      work with and very responsive
      whenever we've had questions.&#8221;
    %p.dude
      Steven Wade
      %br
      Founder, Global Green Arts

- content_for :study_body do

  %h3 What they needed
  %p
    When brothers Steven and David Wade launched their art supply company,
    they needed a site to communicate their vision of sustainable art to
    the world. As veteran designers, they wanted a web studio that could
    deliver perfection down to the pixel. Additionally, the site needed to
    be easily editable to grow and evolve with their company.


  %h3 What we did
  %p 
    We built a heavily customized Wordpress
    installation that perfectly conveys the earthy, art-centered brand of
    Global Green Arts.

  %h3 The results
  %p
    Global Green Arts recently signed their first distribution deal with
    a major chain of art supply stores, and we're excited to continue our
    relationship with them.

app/views/portfolio/helparoundtown.html.haml
- content_for :title do
  Web Application Design, Local Job Markets
- content_for :study_title do
  Help Around Town

- content_for :study_pics do
  
  .body-slideshow{:style => 'height: 400px;'}
    %ul
      %li
        = image_tag 'screenshot-hat1.png'
      %li
        = image_tag 'screenshot-hat2.png'
      %li
        = image_tag 'screenshot-hat3.png'
  :javascript 
    $('.body-slideshow ul li').css('height', '447px');
    $('.body-slideshow').easySlider({
      numeric: true,
      controlsBefore: '<div class="numeric-slide-controls">',
      controlsAfter:  '</div>'
    });

  %blockquote.quote
    -#
      Humanweb built the www.helparoundtown.com website from requirements
      to finished product, from database to GUI.
      This was a partnership, where Humanweb gave me not just deliverables, but
      feedback, advice and opinions on how to create a better site. They functioned
      as full-fledged team members and I must say, now that the project is delivered,
      I miss their input.
    %p
      &#8220;Their commitment to the project, their personal investment
      in seeing it succeed, and the simple pleasure of working with smart, dedicated,
      energized developers, made the process of building a complex website a pleasure.
      I recommend them highly.&#8221;
    %p.dude
      Reem Yared
      %br
      CEO, Help Around Town


- content_for :study_body do
  %p
    How do you create work in a recession? In May 2010, Reem Yared 
    started hearing the same story from friends: their college kids
    were back in town for the summer and could not find work. She decided
    to create job markets where there were none before.

  %h3 What they needed
  %p
    The Help Around Town team approached
    = render('shared/humanweb')
    looking for a full stack of
    design and development services to bootstrap their startup. They needed
    an out-of-the-box team that could investigate their requirements and
    deliver a product.


  %h3 What we did
  %p
    After building prototypes of the site we went forward with development.
    A major concern throughout was to keep the site as open as
    possible while still maintaining strict privacy and parental controls for
    users under the age of 18. We coordinated the launch of the website
    with a local marketing campaign.

  %h3 The results

  %p{:style=>'margin-bottom:0'}
    Features of the site include:
  %ul.disc
    %li weekly job bulletins targeted at a user's interests
    %li secure payment system for posting advertisements
    %li administrative dashboard that gives an overview of site activity
    %li an application process for jobs that protects the privacy of both parties

  %p
    The site provides the groundwork for Help Around Town to grow their
    business and organization over the next year.
    = render('shared/humanweb')
    continues to provide advice and support.

app/views/portfolio/index.html.haml
-content_for :title do
  Portfolio of Work

.image-overlay{:style=>'display:none;'}
  .arrow read more &gt;

.headline-container.center
  %h1 The HUMANWEB Portfolio
  %h2 Showcasing custom-designed web products for our clientele.

.content-area.portfolio
  .row
    .project.grid_4
      %a.screenshot{:href => work_helparoundtown_path}
        = image_tag 'thumb-hat.jpg', :title => 'Help Around Town'
      %h3 Help Around Town
      %p
        A Boston-based startup creates jobs through local, neighborhood-based
        employment boards. Humanweb took the product from
        concept to production, providing a full range of turn-key design and
        development services.

    .project.grid_4
      %a.screenshot{:href => work_purplebinder_path}
        = image_tag 'thumb-pb.png'
      %h3 Purple Binder
      %p
        A lookup tool for social service agencies, like Yelp for the social safety
        net. Currently under development as Humanweb's first product.
  .row
    .project.grid_4
      %a.screenshot{:href => work_rentstuff_path}
        = image_tag 'thumb-rentstuff.png'
      %h3 RentStuff
      %p
        RentStuff is a portal for rentals of all kinds. They hired Humanweb
        to design and build a site for a new sector of their business.

    .project.grid_4
      %a.screenshot{:href => work_southsidehealth_path}
        = image_tag 'thumb-ssh.jpg'
      %h3 &ldquo;SSH&rdquo;
      %p
        A site for a national non-profit to keep track of their referral information for social service agencies.

  .row
    .project.grid_4
      %a.screenshot{:href => work_projectevie_path} 
        = image_tag 'thumb-evie.jpg'
      %h3 Project EVIE
      %p
        A non-profit promoting electric vehicles needed a beautiful
        website and a comprehensive social media campaign.

    .project.grid_4
      %a.screenshot{:href => work_globalgreenarts_path}< 
        = image_tag 'thumb-gga.jpg'
      %h3 Global Green Arts
      %p
        We worked with the veteran graphic designers at Global Green Arts to create
        a promotional site showcasing their line of eco-friendly art materials.

app/views/portfolio/projectevie.html.haml
- content_for :title do
  Social Media Campaign, Web Design, Electric Vehicles
- content_for :study_title do
  Project EVIE

- content_for :study_logo do
  = image_tag 'logo_evie.png'

- content_for :study_sidebar do
  .item.light-green.rounded-small
    %h3 Technology Used
    %ul
      %li HTML5 and CSS3
      %li JavaScript with jQuery
      %li Twitter and Facebook integration
      %li MailChimp for huge mailings

- content_for :study_pics do
  .body-slideshow
    %ul
      %li
        = image_tag 'screenshot-evie1.jpg'
      %li
        = image_tag 'screenshot-evie2.jpg'
      %li
        = image_tag 'screenshot-evie3.jpg'

  :javascript
    $('.body-slideshow ul li').css('height', '420px');
    $('.body-slideshow').easySlider({
      numeric: true,
      controlsBefore: '<div class="numeric-slide-controls">',
      controlsAfter: '</div>'
    });

  %blockquote.quote
    %p
      &#8220;The clean, spacious design of our site goes perfectly with
      our organization's brand.&#8221;
    %p.dude
      %b Jonathan Azrielant
      %br
      Founder, Project EVIE


- content_for :study_body do
  %h3 What they needed
  %p
    
    Project EVIE is a non-profit organization dedicated to promoting the
    adoption of electric vehicles. Humanweb sponsored them by providing
    a beautifully designed web presence.

  %h3 What we did
  %p
    Coordinating with EVIE's marketing team, we designed a site incorporating
    smooth, spacious elements that complemented their organization's brand.
  %p
    After the team planned their route, we created an interactive map
    mini-site that showed the plan for the entire trip. The mini-site
    was used in presentations to top auto industry executives.

  %h3 The result
  %p
    EVIE generated a lot of buzz and raised awareness of fully electric
    vehicles as practical, environmentally superior alternatives.

    %p.center
    %em The Project EVIE organization is now defunct, but the electric vehicle dream lives on.

  %h3 In the press
  %ul
    %li
      = link_to '"Project Evie: Around the world in an electric car"', "http://www.ridelust.com/project-evie-around-the-world-in-an-electric-car/"
      RideLust.com April 9, 2010.
    %li
      = link_to '"Racing Around the World in Electric Cars, Dodging Minefields"', "http://www.thedailygreen.com/living-green/blogs/cars-transportation/electric-car-race-460410"
      The Daily Green April 8, 2010.
    %li
      = link_to '"Around the World in an Electric Car"'
      Change.org Mar 4, 2010.
    %li
      = link_to '"Five Questions: Jon Azrielant, Project EViE Executive Director"', "http://www.greencarreports.com/blog/1042675_five-questions-jon-azrielant-project-evie-executive-director"
      Green Car Reports. Feb 23, 2010.
    %li
      = link_to '"Project Evie Will Drop EV Around Parts Of Globe To Prove Viability"', "http://www.earthtechling.com/2010/02/project-evie-will-drop-ev-around-parts-of-globe-to-prove-viability/"
      EarthTechling. Feb 19, 2010.
    %li
      = link_to '"Project EVIE | Around the world in a production electric vehicle"', "http://www.ekopolitan.com/culture/project-evie-around-world-production-electric-vehicle"
      ekopolitan. Feb 10, 2010.
    %li
      = link_to '"Project EVIE: Around the World in an Electric Car"', "http://www.fastcompany.com/blog/ariel-schwartz/sustainability/project-evie-around-world-electric-car"
      Fast Company. Feb 2, 2010.
    %li
      = link_to "Project Evie getting ready to go 'round the world in an electric car", "http://green.autoblog.com/2010/02/02/project-evie-getting-ready-to-go-round-the-world-in-an-electric/"
      AutoBlog Green. Feb 2, 2010.
    %li
      = link_to "Power Play", "http://www.hemispheresmagazine.com/2010/01/01/power-play/"
      Hemispheres Magazine. Jan 1, 2010.
    %li
      = link_to "Spotlight On... Project EVIE", "http://theleaflet.greenedgenyc.org/December%2009/Non-Profit/Project%20EVIE.html"
      The Leaflet. Dec 1, 2009.

app/views/portfolio/purplebinder.html.haml
- content_for :title do
  Find Social Services
- content_for :study_title do
  Purple Binder

-content_for :study_sidebar do

  .center= image_tag 'thumb-pb.png', :style => 'border: 1px solid #ddd;'
  .item.light-green.rounded-small
    %h3 Technology Used
    %ul
      %li Rails 3.2
      %li Dynamic frontend with EmberJS
      %li Geolocation with Google API
      %li jQuery
      %li HTML5 with CSS3

- content_for :study_logo do
  = image_tag 'thumb-rentstuff.png'

- content_for :study_pics do
  .body-slideshow{:style=>'height: 340px;'}
    %ul
      %li
        = image_tag 'screenshot-pb1.png'
      %li
        = image_tag 'screenshot-pb2.png'
      %li
        = image_tag 'screenshot-pb3.png'
  :javascript 
    $('.body-slideshow ul li').css('height', '387px');
    $('.body-slideshow').easySlider({
      numeric: true,
      controlsBefore: '<div class="numeric-slide-controls">',
      controlsAfter:  '</div>'
    });


- content_for :study_body do
  %p
    Purple Binder is an app that lets you find social services near you. It is
    the first comprehensive, up-to-date directory of Chicago’s social safety
    net. Social workers
    use it to give their clients better referrals and waste less time hunting
    for service providers.

  %p 
    In September 2012, we're rolling out to all of the students of social work in Chicago.
    They will use it at their field placements to give them a head start in their work.

  %p
    Purple Binder stays up to date through its users, who share rather than
    duplicate each others' efforts to find fresh info about Chicago’s social
    services. The app also makes it easy for social workers to collaborate, sharing notes
    and lists of programs.

  %p
    %b The result:
    a social safety network.

app/views/portfolio/rentstuff.html.haml
- content_for :title do
  PHP Development
- content_for :study_title do
  RentStuff

-content_for :study_sidebar do
  .item.light-green.rounded-small
    %h3 Technology Used
    %ul
      %li PHP with CodeIgniter
      %li jQuery
      %li HTML5 with CSS3

- content_for :study_logo do
  = image_tag 'thumb-rentstuff.png'

- content_for :study_pics do
  = image_tag 'screenshot-rentstuff.png', :class => 'screenshot'

- content_for :study_body do
  %p
    After closing a major round of funding in Spring 2012, RentStuff was ready
    to expand their business into a new sector. They hired
    = render 'shared/humanweb'
    to design and build the web application for their new operations.

  %p
    The new application allows rental businesses to more easily manage their business inventory.
    At the same time, it plugs them into the RentStuff marketplace so that they
    have access to RentStuff's broad customer base.

  %p
    Though the new site was developed as a separate piece of software from
    the existing site, it integrates perfectly with the extant database and
    user interface.

  %p
    We had a fantastic time working with RentStuff as they grew their company.

app/views/portfolio/southsidehealth.html.haml
-# This page is currently commented out in routes.rb
-# We took it down as per UCM's request.

- content_for :title do
  Web Application Design, Custom Database Design, Social Services Database
- content_for :study_title do
  &ldquo;SSH&rdquo;

- content_for :study_sidebar do
  -#.sidebar-slideshow
    %ul
      %li
        = image_tag 'screenshot-ssh2.png'
      %li
        = image_tag 'screenshot-ssh1.png'
      %li
        = image_tag 'screenshot-ssh3.png'
      %li
        = image_tag 'screenshot-ssh4.png'
    :javascript
      $('.sidebar-slideshow').easySlider({
        numeric: true,
        controlsBefore: '<div class="numeric-slide-controls">',
        controlsAfter:  '</div>'
      });

  -#.item
    %h3.center In partnership with
    = image_tag 'logo_urbanhealth.png'
    -#%br
    -#= image_tag 'logo_healthleads.png'

  -#= image_tag 'logo_ssh.png'
  .item.light-green.rounded-small
    %h3 Technology Used
    %ul
      %li PHP and CakePHP
      %li Agile development
      %li AJAX, Ext, and jQuery
      %li Weekly user focus groups
      %li Distributed version control with Mercurial
      %li Project management with Kiln and FogBugz
      %li MySQL
      %li Geolocation with the Google API

- content_for :study_pics do
  %blockquote.quote.no-top-margin
    %p.text
      &#8220;I was impressed by their personable handling of large focus groups
      and their ability to draw out subtleties in user motivation. Subsequently they
      translated those subtleties into good design. Though the underlying
      technology is complicated, the user design is simple and inviting.&#8221;

  %blockquote.quote.no-top-border.no-top-margin
    %p
      &#8220;They took a previous contractor's design and re-architected it so the
      site would scale, all the while keeping the site operational for the
      5000+ users who depend on it.&#8221;
    %p.dude
      Director of Technology Projects, Major Chicago Hospital


- content_for :study_body do

  %p
    Humanweb built a site to help staff at a major non-profit find essential resources for
    low-income patients.

  %h3 What they needed
  %p
    When
    =render('shared/humanweb')
    was first approached to develop the site, it was already in
    widespread use despite major issues with stability and user interface. This
    pointed towards a deep-seated need for such an application, and only made
    us more excited to take on the project.



  %h3 What we did
  %p
    We spent the first few weeks updating the look of the site and fixing
    bugs and usability issues. Then,
    = render 'shared/humanweb'
    met with heavy users of the site
    to discover what they liked, what they didn't, and what they wished they
    could do.
    Through weekly meetings with users, we invested them in the development
    process and were able to get immediate feedback from the people to whom
    the site mattered most.


  %h3 The results
  %p
    The site is used every day to connect thousands of
    clients with the social services that they need. By centralizing this information,
    SSH helps to reduce unnecessary emergency
    room visits.

  -#%p.light-grey
    The South Side Health application is open source, licensed under the
    Apache 2.0 license. It is available in a Mercurial
    <a href="http://bitbucket.org/southsidehealth/southsidehealth">repository</a> hosted
    on Bitbucket.
    

app/views/posts/_form.html.haml
- form_for @post do |f|
  .row
    = f.label :title
    = f.text_field :title, :style => 'width: 100%;'
  .row
    = f.label :body
    = f.text_area :body, :style => 'width: 100%;', :rows => '30'
  .row
    = f.label :tech
    = f.check_box :tech
  .row
    = f.submit

app/views/posts/_post.html.haml
- indexpage ||= false

%article
  - if indexpage
      %h1.title
        = link_to post.title, post_path(post)
  - else
    %h1.title= post.title
  %h2= post.created_at.strftime('%B %d, %Y')

  .content-area
    .padding-30 
      .body 
        = BlueCloth.new(post.body).to_html.html_safe

      - unless indexpage
        %p{:style => 'margin-top: 1em;'}
          = link_to 'back to blog', posts_path, :class => 'light-grey'

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/index.html.haml
- @posts.reverse_each do |post|
  = render 'post', :post => post, :indexpage => true

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', :post => @post, :indexpage => false

app/views/shared/_casestudies.html.haml
%ul.case-studies
  %li <b>More Case Studies:</b>
  - unless request.fullpath == work_helparoundtown_path
    %li= link_to "Help Around Town", work_helparoundtown_path, :class => 'text'
  - unless request.fullpath == work_purplebinder_path
    %li= link_to "Purple Binder", work_purplebinder_path, :class => 'text' 
  - unless request.fullpath == work_globalgreenarts_path
    %li= link_to "Global Green Arts", work_globalgreenarts_path, :class => 'text' 
  - unless request.fullpath == work_rentstuff_path
    %li= link_to "RentStuff", work_rentstuff_path, :class => 'text' 
  - unless request.fullpath == work_projectevie_path
    %li= link_to "Project EVIE", work_projectevie_path, :class => 'text'
  - unless request.fullpath == work_southsidehealth_path
    %li= link_to "&ldquo;SSH&rdquo;".html_safe, work_southsidehealth_path, :class => 'text'

app/views/shared/_humanweb.html.haml
HUMANWEB

app/views/shared/_menu.html.haml
#menu
  #bar
    #fobs_container
      %ul
        %li
          %span portfolio
        %li
          %span about us